import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, rm, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { MAX_DESCRIPTION_LENGTH } from '../constants.js';
import { DESCRIPTION_SCAN_WINDOW, firstBodyLine } from '../parsers/body-description.js';
import { parseAgents } from '../parsers/agent-parser.js';
import { parseCommands } from '../parsers/command-parser.js';
import { parseRules } from '../parsers/rule-parser.js';
import { parseSkills } from '../parsers/skill-parser.js';
import { parseSingleFile } from '../parsers/single-file-parser.js';
import { cpuTimeMs } from './cpu-time.js';

let tempDir: string;

beforeEach(async () => {
  tempDir = await mkdtemp(join(tmpdir(), 'cv-desc-fallback-'));
});

afterEach(async () => {
  await rm(tempDir, { recursive: true, force: true });
});

async function parseCommandSource(source: string) {
  const commandsDir = join(tempDir, 'commands');
  await mkdir(commandsDir, { recursive: true });
  await writeFile(join(commandsDir, 'demo.md'), source);
  const result = await parseCommands(commandsDir);
  expect(result.errors).toEqual([]);
  expect(result.entries).toHaveLength(1);
  return result.entries[0];
}

describe('description fallback from the body', () => {
  it('uses the first paragraph line after the heading and marks the provenance', async () => {
    const entry = await parseCommandSource('# Demo\n\nShips the release.\n\nMore detail.\n');

    expect(entry.description).toBe('Ships the release.');
    expect(entry.metadata.descriptionSource).toBe('body');
  });

  it('skips blank lines, every heading level and fenced code blocks', async () => {
    const source = [
      '',
      '# One',
      '',
      '### Three',
      '```bash',
      'echo not-a-description',
      '```',
      '',
      'Real sentence.',
    ].join('\n');

    const entry = await parseCommandSource(source);

    expect(entry.description).toBe('Real sentence.');
  });

  it('strips emphasis, links, inline code and list or quote markers', async () => {
    const source = 'Run **the** [deploy script](https://example.com/x) with `--dry-run` first.';

    expect((await parseCommandSource(source)).description).toBe(
      'Run the deploy script with --dry-run first.',
    );
  });

  it('strips a list marker and a blockquote marker', async () => {
    expect((await parseCommandSource('- Do the thing\n- Other')).description).toBe('Do the thing');
    expect((await parseCommandSource('> Quoted note\n')).description).toBe('Quoted note');
  });

  it('does not treat snake_case words as emphasis', async () => {
    const entry = await parseCommandSource('Reads my_var_name and other_thing_here safely.');

    expect(entry.description).toBe('Reads my_var_name and other_thing_here safely.');
  });

  it('skips lines that carry no text once markdown is removed', async () => {
    const source = [
      '![badge](https://example.com/b.svg)',
      '<objective>',
      '---',
      'Actual text.',
    ].join('\n');

    expect((await parseCommandSource(source)).description).toBe('Actual text.');
  });

  it('skips a one-line HTML comment before the real text', async () => {
    const source = '<!-- markdownlint-disable -->\n\nReal text here';

    expect((await parseCommandSource(source)).description).toBe('Real text here');
  });

  it('skips a multi-line HTML comment and keeps text that follows the closing marker', async () => {
    const source = '<!--\ngenerated by a tool\n\nDo not edit\n-->\nReal text here';

    expect((await parseCommandSource(source)).description).toBe('Real text here');
    expect(firstBodyLine('<!-- a\nb --> after the comment\nlater')).toBe('after the comment');
  });

  it('keeps text on either side of an inline comment and ignores a comment inside a fence', () => {
    expect(firstBodyLine('Before <!-- hidden --> after')).toBe('Before after');
    expect(firstBodyLine('```\n<!--\n```\nReal')).toBe('Real');
    expect(firstBodyLine('<!--\n```\n-->\nReal')).toBe('Real');
  });

  it('closes a fence only with the same character and at least the same length', () => {
    expect(firstBodyLine('````md\n```js\nx\n```\n````\nReal text')).toBe('Real text');
    expect(firstBodyLine('```\n~~~\n```\nReal')).toBe('Real');
    expect(firstBodyLine('~~~\n```\nx\n~~~\nReal')).toBe('Real');
    expect(firstBodyLine('```\ncode\n``` trailing\nmore code\n```\nReal')).toBe('Real');
  });

  it('does not treat a backtick line with a backtick in its info string as a fence', () => {
    expect(firstBodyLine('```js``` is inline code\nNext')).toBe('js is inline code');
  });

  it('does not let a comment marker inside an inline code span open a comment', () => {
    expect(firstBodyLine('Use `<!--` to open a comment.\nSecond')).toBe(
      'Use <!-- to open a comment.',
    );
    const doubleTick = firstBodyLine('Use ``a ` <!-- b`` here\nSecond');
    expect(doubleTick).toContain('<!-- b');
    expect(doubleTick).toContain('here');
    expect(firstBodyLine('Real <!-- note --> and `<!--` code')).toBe('Real and <!-- code');
    expect(firstBodyLine('A `b` <!-- open\nhidden\n--> after')).toBe('A b');
    expect(firstBodyLine('a ` b <!-- c --> d')).toBe('a ` b d');
    const mixedRuns = firstBodyLine('Use `a `` <!-- b` end\nSecond');
    expect(mixedRuns).toContain('<!-- b');
    expect(mixedRuns).toContain('end');
  });

  it('leaves the description empty when the body is only a comment', () => {
    expect(firstBodyLine('<!-- only a note -->')).toBe('');
    expect(firstBodyLine('<!-- never closed\nReal text')).toBe('');
  });

  it('bounds a long first line to the documented length with an ellipsis', async () => {
    const entry = await parseCommandSource('a'.repeat(MAX_DESCRIPTION_LENGTH * 3));

    expect(MAX_DESCRIPTION_LENGTH).toBeLessThanOrEqual(200);
    expect(entry.description).toHaveLength(MAX_DESCRIPTION_LENGTH);
    expect(entry.description.endsWith('…')).toBe(true);
    expect(entry.description.startsWith('a'.repeat(MAX_DESCRIPTION_LENGTH - 1))).toBe(true);
  });

  it('keeps a line that is exactly at the limit whole', async () => {
    const line = 'b'.repeat(MAX_DESCRIPTION_LENGTH);

    expect((await parseCommandSource(line)).description).toBe(line);
  });

  it('never overwrites a real description', async () => {
    const entry = await parseCommandSource('---\ndescription: Written by hand\n---\nBody line.\n');

    expect(entry.description).toBe('Written by hand');
    expect(entry.metadata.descriptionSource).toBeUndefined();
  });

  it('treats a blank description as missing', async () => {
    const entry = await parseCommandSource('---\ndescription: "   "\n---\nBody line.\n');

    expect(entry.description).toBe('Body line.');
    expect(entry.metadata.descriptionSource).toBe('body');
  });

  it('leaves the description empty for a frontmatter-only file', async () => {
    const entry = await parseCommandSource('---\nname: only-meta\n---\n');

    expect(entry.description).toBe('');
    expect(entry.metadata.descriptionSource).toBeUndefined();
  });

  it('leaves the description empty when the body has only headings', async () => {
    const entry = await parseCommandSource('# Title\n\n## Sub\n');

    expect(entry.description).toBe('');
    expect(entry.metadata.descriptionSource).toBeUndefined();
  });

  it('feeds the derived description into tag extraction', async () => {
    const entry = await parseCommandSource('Runs a security review of the diff.');

    expect(entry.tags).toContain('security');
  });

  it('applies to skills and agents as well', async () => {
    const skillsDir = join(tempDir, 'skills');
    await mkdir(join(skillsDir, 'alpha'), { recursive: true });
    await writeFile(join(skillsDir, 'alpha', 'SKILL.md'), '# Alpha\n\nSkill body text.\n');
    const agentsDir = join(tempDir, 'agents');
    await mkdir(agentsDir, { recursive: true });
    await writeFile(join(agentsDir, 'beta.md'), '---\nname: beta\n---\nAgent body text.\n');

    const [skill] = (await parseSkills(skillsDir)).entries;
    const [agent] = (await parseAgents(agentsDir)).entries;

    expect(skill.description).toBe('Skill body text.');
    expect(skill.metadata.descriptionSource).toBe('body');
    expect(agent.description).toBe('Agent body text.');
    expect(agent.metadata.descriptionSource).toBe('body');
  });

  it('gives a rule with a blank description the same heading fallback as a missing one', async () => {
    const rulesDir = join(tempDir, 'rules');
    await mkdir(rulesDir, { recursive: true });
    await writeFile(join(rulesDir, 'style.md'), '---\ndescription: ""\n---\n# Style Guide\n');

    const [rule] = (await parseRules(rulesDir)).entries;

    expect(rule.description).toBe('Style Guide');
  });

  it.each([
    ['blank with a heading', '---\nname: r\ndescription: ""\n---\n# Heading rule\n\nBody.\n'],
    ['blank with whitespace', '---\nname: r\ndescription: "   "\n---\n# Heading rule\n'],
    ['blank without a heading', '---\nname: r\ndescription: ""\n---\nBody only.\n'],
    ['missing with a heading', '---\nname: r\n---\n# Heading rule\n'],
    ['declared', '---\nname: r\ndescription: Declared text\n---\n# Heading rule\n'],
  ])(
    'gives a %s rule the same description from a scan and a single-file re-parse',
    async (_l, src) => {
      const rulesDir = join(tempDir, 'rules');
      await mkdir(rulesDir, { recursive: true });
      const filePath = join(rulesDir, 'r.md');
      await writeFile(filePath, src);

      const [scanned] = (await parseRules(rulesDir)).entries;
      const single = await parseSingleFile(filePath, 'rule');

      expect(single?.description).toBe(scanned.description);
      expect(single?.description).not.toBe('');
    },
  );

  it('matches between a directory scan and a single-file re-parse', async () => {
    const commandsDir = join(tempDir, 'commands');
    await mkdir(commandsDir, { recursive: true });
    const filePath = join(commandsDir, 'demo.md');
    await writeFile(filePath, '# Demo\n\nShips the release.\n');

    const scanned = (await parseCommands(commandsDir)).entries[0];
    const single = await parseSingleFile(filePath, 'command');

    expect(single?.description).toBe(scanned.description);
    expect(single?.metadata.descriptionSource).toBe('body');
  });

  it('strips star emphasis and strikethrough', async () => {
    const entry = await parseCommandSource('Use *this* and ~~that~~ carefully.');

    expect(entry.description).toBe('Use this and that carefully.');
  });

  it('never cuts a surrogate pair in half when it truncates', async () => {
    const entry = await parseCommandSource(
      `${'x'.repeat(MAX_DESCRIPTION_LENGTH - 2)}😀${'y'.repeat(10)}`,
    );

    expect(entry.description.length).toBeLessThanOrEqual(MAX_DESCRIPTION_LENGTH);
    expect(entry.description.endsWith('…')).toBe(true);
    expect(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(entry.description)).toBe(false);
  });

  it('derives the same description for skills and agents on the single-file path', async () => {
    const skillDir = join(tempDir, 'skills', 'alpha');
    await mkdir(skillDir, { recursive: true });
    const skillPath = join(skillDir, 'SKILL.md');
    await writeFile(skillPath, '# Alpha\n\nSkill body text.\n');
    const agentPath = join(tempDir, 'beta.md');
    await writeFile(agentPath, '---\nname: beta\n---\nAgent body text.\n');

    const skill = await parseSingleFile(skillPath, 'skill');
    const agent = await parseSingleFile(agentPath, 'agent');

    expect(skill?.description).toBe('Skill body text.');
    expect(skill?.metadata.descriptionSource).toBe('body');
    expect(agent?.description).toBe('Agent body text.');
    expect(agent?.metadata.descriptionSource).toBe('body');
  });

  it('keeps a real description on the single-file path', async () => {
    const filePath = join(tempDir, 'agent.md');
    await writeFile(filePath, '---\nname: x\ndescription: Hand written\n---\nBody line.\n');

    const single = await parseSingleFile(filePath, 'agent');

    expect(single?.description).toBe('Hand written');
    expect(single?.metadata.descriptionSource).toBeUndefined();
  });
});

describe('description fallback on a pathological line', () => {
  const PATHOLOGICAL_LINE_REPEATS = 20_000;
  // A wall-clock budget failed on a loaded machine (load 30-160) with 1.0-2.3 s measured for ~0.1 s
  // of CPU: the vitest worker was descheduled, the code was not slow. CPU time counts only
  // scheduled time. Measured on a 2024 M-series: the real cost is <= 0.11 s per case idle (~0.15 s
  // at load 64), so 1 s is ~9x headroom. The quadratic regressions this guards: dropping the scan
  // window costs 1.3-5.8 s on each of the four opener cases ("[a](" is the cheapest, 1.3-2.1 s);
  // dropping the indexOf cache in removeComments costs 2.6-3.7 s on "`x` " and 5.2-6.9 s on
  // "`` x `` " (its "`a " case lands at 1.0-1.4 s, around the budget, and is not relied on). The
  // budget is not lowered to widen those margins: a slower CI core (Windows runner) multiplies the
  // real cost, and headroom there is what this budget exists to keep. process.cpuUsage is
  // process-wide, so this budget assumes the file stays sequential (no `.concurrent`).
  const CPU_BUDGET_MS = 1_000;

  // Each opener is never closed, which is what makes an unbounded inline-markdown regex rescan.
  it.each(['**a ', '~~a ', '[a](', '![a]('])('stays fast on one very long line of "%s"', (unit) => {
    const line = unit.repeat(PATHOLOGICAL_LINE_REPEATS);

    const { result: text, cpuMs } = cpuTimeMs(() => firstBodyLine(line));

    expect(cpuMs).toBeLessThan(CPU_BUDGET_MS);
    expect(text.length).toBeGreaterThan(0);
    expect(text.length).toBeLessThanOrEqual(MAX_DESCRIPTION_LENGTH);
  });

  // Each unit opens or closes a code span, which is what made comment removal rescan the line.
  const BACKTICK_LINE_REPEATS = 200_000;
  const DISTINCT_RUN_LENGTHS = 1_500;

  it.each(['`x` ', '`a ', '`` x `` ', '`a` <!-- c --> '])(
    'stays fast on one very long line of code spans "%s"',
    (unit) => {
      const line = unit.repeat(BACKTICK_LINE_REPEATS);

      const { result: text, cpuMs } = cpuTimeMs(() => firstBodyLine(line));

      expect(cpuMs).toBeLessThan(CPU_BUDGET_MS);
      expect(text.length).toBeGreaterThan(0);
      expect(text.length).toBeLessThanOrEqual(MAX_DESCRIPTION_LENGTH);
    },
  );

  it('stays fast when every backtick run has a different length and none closes', () => {
    const runs = Array.from({ length: DISTINCT_RUN_LENGTHS }, (_, i) => `${'`'.repeat(i + 1)}a `);
    const line = runs.join('');

    const { result: text, cpuMs } = cpuTimeMs(() => firstBodyLine(line));

    expect(cpuMs).toBeLessThan(CPU_BUDGET_MS);
    expect(text.length).toBeGreaterThan(0);
  });

  it('never leaves half a surrogate pair where the scanned prefix is cut', () => {
    // Whitespace collapses, so the high surrogate that ends the window survives stripping.
    const line = `ok${' '.repeat(DESCRIPTION_SCAN_WINDOW - 3)}\u{1F600}`;

    const text = firstBodyLine(line);

    expect(text).toBe('ok');
  });
});
